apiVersion: v1
kind: Service
metadata:
  name: haul-api
  namespace: haul
  labels:
    app: haul-api
spec:
  type: ClusterIP
  selector:
    app: haul-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
