apiVersion: v1
kind: Secret
metadata:
  name: haul-secrets
  namespace: haul
type: Opaque
stringData:
  DATABASE_URL: "postgresql://neondb_owner:npg_fRVtNsJ9gLz3@ep-gentle-thunder-aqcmkpdh-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
  JWT_SECRET: "dsankjdh0123hjodnfkhsd98cvnsdoirf230rfjpdspfodfj0d9ffmldkfgnsdfklgnbsdflgnsdfojdfnsdfoijds"
  GOOGLE_PLACES_KEY: "AIzaSyDPl1MIrQouy7u01UgJS4Almt1HKBRB22s"
  GOOGLE_ROUTES_KEY: "AIzaSyDPl1MIrQouy7u01UgJS4Almt1HKBRB22s"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "465"
  SMTP_USER: "christopher.L4n@gmail.com"
  SMTP_PASS: "xwdh oerw whne cdkl"
  CLIENT_URL: "http://localhost:5173"